apiVersion: v1
kind: Pod

metadata:
  name: nginx-2
  labels:
    env: production
    
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m" 